config/routes.rb
Rails.application.routes.draw do

  get "users/new"
  root "static_pages#home"
  get "signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    resources :relationships, only: :index
  end

  resources :entries, only: [:create, :destroy] do
    #resources :comments, only: :create
  end

  resources :relationships, only: [:create, :destroy]

  resources :comments, only: [:create, :destroy]
end

app/views/shared/_entry_form.html.erb
<%= form_for @entry, remote: true do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_field :title, placeholder: "Title" %>
    <%= f.text_area :content, placeholder: "Compose new entry..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize object.errors.count, "error" %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items.order_by_time %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to user_relationships_path user_id: @user, type: "following" do %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  <% end %>
  <%= link_to user_relationships_path user_id: @user, type: "followers" do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize current_user.entries.count, "entry" %></span>